version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - RCON_HOST=folia
      - RCON_PORT=25575
      - RCON_PASSWORD=${RCON_PASSWORD}
    external_links:
      - folia

networks:
  default:
    external: true
    name: winter25-folia-gqcqwv_default