version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - RCON_HOST=172.19.0.2
      - RCON_PORT=25575
      - RCON_PASSWORD=${RCON_PASSWORD}
      - SERVERID_JESSY=${SERVERID_JESSY}
      - ROLEID_JESSY=${ROLEID_JESSY}
      - SERVERID_MALLE=${SERVERID_MALLE}
      - ROLEID_MALLE=${ROLEID_MALLE}
      - SERVERID_BOOMII=${SERVERID_BOOMII}
      - ROLEID_BOOMII=${ROLEID_BOOMII}
    external_links:
      - folia
networks:
  default:
    external: true
    name: winter25-folia-gqcqwv_default